apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: elastichq
  namespace: elastic-hq
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: elastichq
  minReplicas: 4
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 100
  - type: Resource    
    resource:
      name: cpu 
      target:
          type: Utilization
          averageUtilization: 50