apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  notifiers.yaml: |
    email:
      host: smtp.gmail.com
      port: 587
      from: <myemail>@gmail.com
      username: <myemail>@gmail.com
      password: <mypassword>
    slack:
      token: xoxb-1154186453170-1370505488224-ek8Uu9lprVTiByP4J1GyPrp3
      username: @here