apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  labels:
    io.kompose.service: elastichq
  name: elastichq
  namespace: elastic-hq
spec:
  selector:
    replicas: 3
  template:
    metadata:
      labels:
        io.kompose.service: elastichq
        workstations: ingress
        workstations-ingress-http-alt: allow
        name: elastichq
    spec:
      containers:
      - image: elastichq/elasticsearch-hq:latest
        name: elastichq
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 500Mi
            cpu: 200m
          requests:
            memory: 100Mi
            cpu: 10m
      restartPolicy: Always
status: {}
