apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastichq
  namespace: elastic-hq
  labels:
    io.kompose.service: elastichq
spec:
  selector:
    matchLabels:
      app: elastic-hq
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: elastic-hq
    spec:
      containers:
      - name: elastichq
        image: elastichq/elasticsearch-hq:release-v3.5.12
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 500Mi
            cpu: 200m
          requests:
            memory: 100Mi
            cpu: 10m