apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: elastichq
  name: elastichq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elastichq
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/esnet: "true"
        io.kompose.service: elastichq
    spec:
      containers:
      - env:
        - name: HQ_CA_CERTS
          value: /usr/local/share/ca-certificates/MYCA.crt
        - name: HQ_DEBUG
          value: "True"
        - name: HQ_DEFAULT_URL
          value: http://elasticsearch:9200
        - name: HQ_ENABLE_SSL
          value: "True"
        - name: HQ_VERIFY_CERTS
          value: "False"
        image: elasticsearch-hq:develop
        imagePullPolicy: ""
        name: elastichq
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
