apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: resize-hpa-elastic
  namespace: elastic-hq
spec:
  minReplicas: 3
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: elastichq
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        targetAverageUtilization: 100
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        targetAverageUtilization: 100