apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: elastichq
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: elastichq
  targetCPUUtilizationPercentage: 50