apiVersion: v1
kind: Service
metadata:
  name: elastichq
  namespace: elastic-hq
spec:
  selector:
    app: elastic-hq
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
status:
  loadBalancer: {}