apiVersion: v1
kind: Namespace
metadata:
  name: elastic-hq
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elastichq
  name: elastichq
  namespace: elastic-hq
spec:
  ports:
  - name: service-port
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: elastichq
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastichq
  namespace: elastic-hq
spec:
  selector:
    matchLabels:
      app: elastic-hq
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: elastic-hq
    spec:
      containers:
      - name: elastichq
        image: elastichq/elasticsearch-hq:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
          requests:
            memory: 50Mi
            cpu: 50m