apiVersion: v1
kind: Namespace
metadata:
  name: example-app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-app
  name: example-service
  namespace: example-app
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: example-app
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
  namespace: example-app
  labels:
    app: example-app
  annotations:
    application: development
spec:
  selector:
    matchLabels:
      app: example-app
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: aimvector/python:3
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: 100Mi
            cpu: 100m
          requests:
            memory: 50Mi
            cpu: 50m