apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/moonshot-cloudnative/cloudnative-argoproj.git
    targetRevision: init-rollouts
    path: rollouts
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: false
      selfHeal: false