apiVersion: v1
kind: Namespace
metadata:
  name: ms-proxy
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: ms-proxy
spec:
  ports:
    - port: 4000
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-proxy
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: ms-proxy
  labels:
    app: nginx-proxy
  annotations:
    application: development
spec:
  selector:
    matchLabels:
      app: nginx-proxy
  replicas: 10
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: ms-proxy
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 50Mi
            cpu: 50m
          requests:
            memory: 20Mi
            cpu: 20m